import type {
  Program,
  Internship,
  Resource,
  SuccessStory,
  PlacementRecord,
  Webinar,
} from "@/lib/types"

export const programs: Program[] = [
  {
    id: "10000000-0000-0000-0000-000000000001",
    slug: "python-full-stack-development",
    title: "Python Full Stack Development",
    description:
      "Become a job-ready Python full-stack developer. Build production applications with Python, Django, FastAPI, React, and PostgreSQL while working on real client briefs alongside an industry mentor.",
    category: "Engineering",
    mode: "Offline",
    duration_weeks: 16,
    price_mrp: 49999,
    price_selling: 34999,
    thumbnail_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    instructor_name: "Aravind Menon",
    city: "Bengaluru",
    skills: ["Python", "Django", "FastAPI", "React", "PostgreSQL", "SQLAlchemy"],
    rating: 4.9,
    enrolled: 2400,
    popular: true,
    curriculum: [
      { week: 1, topic: "Python & Web Foundations", description: "Python, OOP, typing, virtual environments, and testing." },
      { week: 5, topic: "Django Application Development", description: "Django models, REST Framework, authentication, and admin workflows." },
      { week: 9, topic: "FastAPI & React Integration", description: "Async APIs, Pydantic, React components, and API-driven interfaces." },
      { week: 13, topic: "Production Delivery & Guild Placement", description: "PostgreSQL, Redis, Docker, CI/CD, and cloud deployment." },
    ],
    faqs: [
      { question: "Is this program fully offline?", answer: "Yes, classes run in-person at our Koramangala, Bengaluru center." },
      { question: "Do I need prior coding experience?", answer: "No. We start from foundations and ramp up quickly." },
      { question: "Is a certificate provided?", answer: "Yes, a QR-verifiable certificate is issued on completion." },
    ],
  },
  {
    id: "20000000-0000-0000-0000-000000000002",
    slug: "data-analyst",
    title: "Data Analyst",
    description:
      "Learn to turn business data into clear decisions with Python, SQL, Excel, Power BI, Tableau, and practical statistical analysis.",
    category: "Data",
    mode: "Offline",
    duration_weeks: 12,
    price_mrp: 59999,
    price_selling: 42999,
    thumbnail_url: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80",
    instructor_name: "Dr. Sneha Rao",
    city: "Bengaluru",
    skills: ["Python", "SQL", "Excel", "Pandas", "Power BI", "Tableau"],
    rating: 4.9,
    enrolled: 1860,
    popular: true,
    curriculum: [
      { week: 1, topic: "Data Analysis with Python", description: "Python, Jupyter, NumPy, Pandas, and data cleaning workflows." },
      { week: 4, topic: "SQL & Business Metrics", description: "Joins, CTEs, window functions, KPI design, and query optimization." },
      { week: 7, topic: "Statistics & Data Visualization", description: "Descriptive statistics, hypothesis testing, Matplotlib, and Seaborn." },
      { week: 10, topic: "Dashboards & Analyst Projects", description: "Excel, Power BI, Tableau, stakeholder storytelling, and portfolio projects." },
    ],
    faqs: [
      { question: "Which tools will I learn?", answer: "Python, SQL, Excel, Pandas, NumPy, Matplotlib, Seaborn, Power BI, and Tableau." },
      { question: "Do I need prior analytics experience?", answer: "No. We start with practical foundations and build toward portfolio-ready business analyses." },
    ],
  },
  {
    id: "30000000-0000-0000-0000-000000000003",
    slug: "data-engineering",
    title: "Data Engineering",
    description:
      "Build scalable big data pipelines, distributed processing engines, and cloud data warehouses with Apache Spark, Kafka, Snowflake, and dbt.",
    category: "Data",
    mode: "Offline",
    duration_weeks: 14,
    price_mrp: 54999,
    price_selling: 39999,
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    instructor_name: "Dr. Sneha Rao & Aravind Menon",
    city: "Bengaluru",
    skills: ["Python", "SQL", "Apache Spark", "Apache Kafka", "Snowflake", "dbt"],
    rating: 4.8,
    enrolled: 1320,
    curriculum: [
      { week: 1, topic: "Advanced SQL & Dimensional Modeling", description: "Star schemas, window functions, query tuning." },
      { week: 4, topic: "Distributed Processing with PySpark", description: "DataFrames, RDDs, Delta Lake ACID transactions." },
      { week: 8, topic: "Real-Time Streaming with Kafka", description: "Topics, partitions, structured streaming." },
      { week: 11, topic: "Cloud Warehousing & Orchestration", description: "Snowflake, dbt transformations, Apache Airflow DAGs." },
    ],
    faqs: [
      { question: "Will I build live pipelines?", answer: "Yes, real-time clickstream streaming and Medallion Lakehouse projects." },
    ],
  },
]

export const internships: Internship[] = [
  {
    id: "int_frontend_technova",
    slug: "frontend-developer-intern-technova",
    title: "Frontend Developer Intern",
    company_name: "TechNova",
    description:
      "Work with our product team to build delightful, accessible interfaces in React. You'll ship features to production and collaborate closely with designers.",
    sector: "Software",
    location: "Bengaluru",
    mode: "Hybrid",
    stipend: 25000,
    duration_months: 6,
    openings: 3,
    required_degree: "B.Tech / BCA",
    required_branch: "CSE / IT",
    min_cgpa: 7.0,
    deadline: "2026-07-30",
    status: "Active",
    skills: ["React", "TypeScript", "CSS", "Git"],
    responsibilities: [
      "Build and maintain UI components",
      "Collaborate with designers on new features",
      "Write clean, tested, accessible code",
    ],
  },
  {
    id: "int_data_finedge",
    slug: "data-analyst-intern-finedge",
    title: "Data Analyst Intern",
    company_name: "FinEdge",
    description:
      "Help our analytics team turn financial data into insight. Build dashboards, run SQL analyses and support data-driven product decisions.",
    sector: "Fintech",
    location: "Remote",
    mode: "Remote",
    stipend: 20000,
    duration_months: 4,
    openings: 2,
    required_degree: "Any graduate",
    required_branch: "Any",
    min_cgpa: 6.5,
    deadline: "2026-07-15",
    status: "Active",
    skills: ["SQL", "Python", "Excel", "Power BI"],
    responsibilities: [
      "Build dashboards and reports",
      "Run ad-hoc data analyses",
      "Maintain data quality",
    ],
  },
  {
    id: "int_growth_blueorbit",
    slug: "growth-marketing-intern-blueorbit",
    title: "Growth Marketing Intern",
    company_name: "BlueOrbit",
    description:
      "Drive growth experiments across channels. You'll own campaigns end to end and learn how a fast-moving SaaS team acquires and retains customers.",
    sector: "SaaS",
    location: "Pune",
    mode: "On-site",
    stipend: 18000,
    duration_months: 3,
    openings: 2,
    required_degree: "Any graduate",
    required_branch: "Any",
    min_cgpa: 6.0,
    deadline: "2026-06-30",
    status: "Active",
    skills: ["SEO", "Content", "Analytics", "Social Media"],
    responsibilities: [
      "Plan and run growth campaigns",
      "Analyse funnel metrics",
      "Create marketing content",
    ],
  },
  {
    id: "int_uiux_skyline",
    slug: "ui-ux-design-intern-skyline-labs",
    title: "UI/UX Design Intern",
    company_name: "Skyline Labs",
    description:
      "Join our product design studio. Contribute to research, wireframes and high-fidelity prototypes for products used by thousands of people.",
    sector: "Product",
    location: "Hyderabad",
    mode: "Hybrid",
    stipend: 22000,
    duration_months: 6,
    openings: 1,
    required_degree: "Any graduate",
    required_branch: "Design / Any",
    min_cgpa: 6.5,
    deadline: "2026-08-10",
    status: "Active",
    skills: ["Figma", "Prototyping", "User Research"],
    responsibilities: [
      "Support design research",
      "Create wireframes and prototypes",
      "Maintain the design system",
    ],
  },
  {
    id: "int_backend_quanthub",
    slug: "backend-engineer-intern-quanthub",
    title: "Backend Engineer Intern",
    company_name: "QuantHub",
    description:
      "Build scalable APIs and services in Node.js. Work on real systems handling production traffic with mentorship from senior engineers.",
    sector: "Software",
    location: "Bengaluru",
    mode: "On-site",
    stipend: 28000,
    duration_months: 6,
    openings: 2,
    required_degree: "B.Tech / MCA",
    required_branch: "CSE / IT",
    min_cgpa: 7.5,
    deadline: "2026-07-20",
    status: "Active",
    skills: ["Node.js", "PostgreSQL", "REST APIs", "Docker"],
    responsibilities: [
      "Develop and maintain backend services",
      "Design database schemas",
      "Write automated tests",
    ],
  },
  {
    id: "int_ml_neuralcraft",
    slug: "machine-learning-intern-neuralcraft",
    title: "Machine Learning Intern",
    company_name: "NeuralCraft",
    description:
      "Train and evaluate ML models for real products. Get hands-on with data pipelines, experimentation and model deployment.",
    sector: "AI",
    location: "Remote",
    mode: "Remote",
    stipend: 30000,
    duration_months: 6,
    openings: 2,
    required_degree: "B.Tech / M.Tech",
    required_branch: "CSE / Data Science",
    min_cgpa: 7.5,
    deadline: "2026-08-01",
    status: "Active",
    skills: ["Python", "PyTorch", "ML", "Pandas"],
    responsibilities: [
      "Build and train ML models",
      "Run experiments and evaluations",
      "Support model deployment",
    ],
  },
]

export const successStories: SuccessStory[] = [
  {
    id: "ss_1",
    student_name: "Priya Sharma",
    photo_url: null,
    program: "Full-Stack Web Development",
    company: "TechNova",
    package_lpa: 9.5,
    testimonial:
      "I joined with zero coding background. The offline classes and real internship gave me the confidence and portfolio to land a frontend role.",
  },
  {
    id: "ss_2",
    student_name: "Arjun Verma",
    photo_url: null,
    program: "Data Science & Analytics",
    company: "FinEdge",
    package_lpa: 11.0,
    testimonial:
      "The capstone project was exactly the kind of work I now do daily. Mentors pushed me hard and it paid off with a great offer.",
  },
  {
    id: "ss_3",
    student_name: "Sneha Patel",
    photo_url: null,
    program: "UI/UX Product Design",
    company: "Skyline Labs",
    package_lpa: 8.0,
    testimonial:
      "From confused fresher to confident designer. The portfolio reviews and internship made all the difference in interviews.",
  },
]

export const placements: PlacementRecord[] = [
  { id: "pl_1", student_name: "Priya Sharma", company_name: "TechNova", role: "Frontend Engineer", package_lpa: 9.5, program: "Full-Stack Web Development" },
  { id: "pl_2", student_name: "Arjun Verma", company_name: "FinEdge", role: "Data Analyst", package_lpa: 11.0, program: "Data Science & Analytics" },
  { id: "pl_3", student_name: "Sneha Patel", company_name: "Skyline Labs", role: "Product Designer", package_lpa: 8.0, program: "UI/UX Product Design" },
  { id: "pl_4", student_name: "Rohit Nair", company_name: "QuantHub", role: "Backend Engineer", package_lpa: 12.5, program: "Cloud & DevOps Engineering" },
  { id: "pl_5", student_name: "Ananya Singh", company_name: "NeuralCraft", role: "ML Engineer", package_lpa: 14.0, program: "Applied AI & GenAI" },
  { id: "pl_6", student_name: "Vikram Reddy", company_name: "BlueOrbit", role: "Growth Marketer", package_lpa: 7.5, program: "Digital Marketing Pro" },
]

export const resources: Resource[] = [
  {
    id: "res_1",
    slug: "how-to-land-your-first-tech-internship",
    title: "How to Land Your First Tech Internship in 2026",
    excerpt:
      "A practical, step-by-step playbook to go from no experience to a paid internship offer — projects, outreach and interview prep that actually work.",
    content:
      "Landing your first internship feels impossible until you have a system. Start by picking one track and building two portfolio projects that solve real problems. Next, craft a one-page resume that leads with impact. Then run focused outreach: 10 quality applications a week beats 100 generic ones. Finally, prepare for interviews by practising out loud and reviewing fundamentals daily.\n\nThe students who succeed treat the search like a project with weekly goals. Track every application, follow up politely, and iterate on feedback. Consistency compounds.",
    category: "Career",
    author: "Intern Academy Team",
    thumbnail_url: null,
    published_at: "2026-05-20",
    read_minutes: 6,
    is_ai_generated: false,
  },
  {
    id: "res_2",
    slug: "react-vs-the-rest-choosing-your-first-framework",
    title: "React vs the Rest: Choosing Your First Framework",
    excerpt:
      "Overwhelmed by JavaScript frameworks? Here's a clear, opinionated guide to picking one and going deep instead of wide.",
    content:
      "Beginners lose months hopping between frameworks. The truth: the fundamentals transfer. Learn JavaScript deeply, then pick React for its job market and ecosystem. Build real projects, read source code, and only explore alternatives once you're comfortable.\n\nDepth beats breadth early in your career. Employers hire for problem-solving, not framework trivia.",
    category: "Engineering",
    author: "Aravind Menon",
    thumbnail_url: null,
    published_at: "2026-05-08",
    read_minutes: 5,
    is_ai_generated: true,
  },
  {
    id: "res_3",
    slug: "build-a-data-portfolio-that-gets-interviews",
    title: "Build a Data Portfolio That Gets You Interviews",
    excerpt:
      "Three project ideas and a structure that turns raw analysis into a portfolio recruiters can't ignore.",
    content:
      "A strong data portfolio tells a story: question, data, method, insight, impact. Choose datasets you care about, document your process clearly, and ship a clean dashboard. Recruiters skim — make your results obvious in the first ten seconds.\n\nInclude one end-to-end machine learning project, one dashboard, and one analysis with a business recommendation.",
    category: "Data",
    author: "Dr. Sneha Rao",
    thumbnail_url: null,
    published_at: "2026-04-28",
    read_minutes: 7,
    is_ai_generated: true,
  },
  {
    id: "res_4",
    slug: "offline-vs-online-learning-what-actually-works",
    title: "Offline vs Online Learning: What Actually Works",
    excerpt:
      "Completion rates, accountability and outcomes — an honest look at why offline cohorts still win for career switchers.",
    content:
      "Online courses have a completion problem. Offline cohorts solve it with accountability, peer energy and direct mentorship. The data is clear: students in structured, in-person programs finish more, build more and get placed faster.\n\nThe magic is in the environment — showing up, building with peers, and getting immediate feedback.",
    category: "Career",
    author: "Intern Academy Team",
    thumbnail_url: null,
    published_at: "2026-04-12",
    read_minutes: 5,
    is_ai_generated: false,
  },
]

export const webinars: Webinar[] = [
  {
    id: "web_1",
    slug: "breaking-into-product-design",
    title: "Breaking Into Product Design",
    description: "A live session on building a design portfolio and acing UX interviews.",
    thumbnail_url: null,
    scheduled_at: "2026-07-05T18:00:00.000Z",
    duration_mins: 60,
    platform: "Zoom",
  },
  {
    id: "web_2",
    slug: "ai-careers-2026",
    title: "AI Careers in 2026: Where the Jobs Are",
    description: "Industry experts break down the most in-demand AI roles and how to prepare.",
    thumbnail_url: null,
    scheduled_at: "2026-07-18T18:00:00.000Z",
    duration_mins: 75,
    platform: "YouTube Live",
  },
]
